included:
  - Sources
  - Tests
excluded:
  - Pods
opt_in_rules:
  - anonymous_argument_in_multiline_closure
  - array_init
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_init
  - fallthrough
  - file_name_no_space
  - implicitly_unwrapped_optional
  - indentation_width
  - multiline_parameters