# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Build an app with Debug env"
  lane :build_dev do
    build_package({ :configuration => "Debug", :export_method => "ad-hoc" })
    notification_options = {
      :message => "Finished #{lane_context[SharedValues::LANE_NAME]} on #{Time.new.to_s}"
    }
    notify_message(notification_options)
  end

  desc "Build an app with Uat env"
  lane :build_uat do
    build_package({ :configuration => "Uat", :export_method => "ad-hoc" })
    notification_options = {
      :message => "Finished #{lane_context[SharedValues::LANE_NAME]} on #{Time.new.to_s}"
    }
    notify_message(notification_options)
  end

  desc "Build an app with Staging env"
  lane :build_staging do
    build_package({ :configuration => "Staging", :export_method => "ad-hoc" })
    notification_options = {
      :message => "Finished #{lane_context[SharedValues::LANE_NAME]} on #{Time.new.to_s}"
    }
    notify_message(notification_options)
  end

  desc "Build an app with Release env"
  lane :build_release do
    build_package({ :configuration => "Release", :export_method => "app-store" })
    notification_options = {
      :message => "Finished #{lane_context[SharedValues::LANE_NAME]} on #{Time.new.to_s}"
    }
    notify_message(notification_options)
  end

  desc "Runs all the unit tests"
  lane :unit_tests do
    run_tests(scheme: "ARK-iOS")
  end

  desc "Runs all the static check"
  lane :check do
    lint_base({ :mode => :lint })
  end

  desc "Autocorrect all swift files"
  lane :lint_correct do
    lint_base({ :mode => :fix })
  end



  private_lane :lint_base do |options|
    swiftlint(
      mode: options[:mode],
      strict: true,
      executable: "./Pods/SwiftLint/swiftlint",
      config_file: "./.swiftlint.yml",
      output_file: "./fastlane/report.md",
      reporter: "markdown",
      raise_if_swiftlint_error: true,   
      ignore_exit_status: true
    )
  end

  private_lane :build_package do |options|
    build_app(
      workspace: "ARK-iOS.xcworkspace",
      scheme: "ARK-iOS",
      configuration: options[:configuration],
      export_method: options[:export_method],
      silent: false,
      clean: false,
      skip_codesigning: true,
      output_directory: "./build/packages", 
      include_bitcode: false
    )
  end

  desc "Notify message to user"
  private_lane :notify_message do |options|
    if is_ci
      notification_slack(options)
    else
      notification_mac(options)
    end
  end

  private_lane :notification_mac do |options|
    notification(subtitle: "Finished Building", message: options[:message])
  end

  private_lane :notification_slack do |options|
    # For security, we put this value to env.
    # You can find this value in ".env.default" file
    slack_url = ENV["SLACK_URL"]
    slack(
      slack_url: slack_url,
      message: options[:message],
      success: true,
      payload: {
        "Build Date" => Time.new.to_s,
        "Built by" => "Jenkins",
      },
      default_payloads: [:git_branch, :git_author]
    )
  end

  before_all do |lane|
    sh "export LC_ALL=en_US.UTF-8"
    sh "export LANG=en_US.UTF-8"
  end
end
