source 'https://cdn.cocoapods.org/'

platform :ios, '14.0'

target 'Core' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ARK-iOS

  target 'CoreTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
end
