source 'https://cdn.cocoapods.org/'

platform :ios, '14.0'

use_frameworks!

target 'Samples' do
  use_frameworks!
  
  pod 'Core', :path => '../Core', :testspecs => ['Tests']
  pod 'UI', :path => '../UI'

  target 'SamplesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SamplesUITests' do
  end

end
